theme: jekyll-theme-minimal
title: CoFi
description: The Collaborative Finance side of the Cosmos
show_downloads: "true"

# Fix the download links
# TODO Automate generation of these to point to latest release
github:
  zip_url: https://github.com/informalsystems/apalache/releases/latest/download/apalache.zip
  tar_url: https://github.com/informalsystems/apalache/releases/latest/download/apalache.tgz
